<?php
//10 controller
include "controller/Database.php";
include "controller/Session.php";
include "controller/UserData.php";
include "controller/Executor.php";
include "controller/IpLogger.php";
include "controller/class.upload.php";

//11 model
include "model/UserData.php";
include "model/UserTypeData.php";
include "model/StatusData.php";

include "model/EColorInterpretationData.php";
include "model/ColorData.php";
// 12 nov 2013
include "model/TestData.php";
include "model/TestDoData.php";
include "model/ColorInterpretationResultData.php";

// 13 nov 2013
include "model/GradeData.php";
include "model/TeamData.php";
include "model/UserTeamData.php";

// 14 nov 2013
include "model/16FPCategoryData.php";
include "model/16FPAnswerData.php";
include "model/16FPQuestionData.php";
include "model/16FPResultData.php";



?>